services:
  app:
   build:
    context: .
    dockerfile: Dockerfile
   ports:
    - "3000:3000"
    - "5555:5555"
   env_file:
     - ./.env
   depends_on:
    - postgres
  
  postgres:
   image: postgres:15
   ports:
    - "5432:5432"
   environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
   env_file:
    - ./.env
   volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: